[package]
name = "kuchenblech"
version = "0.1.0"
authors = ["Andreas Stührk <andy@hammerhartes.de>"]
edition = "2018"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
warp = "0.3"
